apiVersion: v1
kind: Service
metadata:
  name: building-block-name
  labels:
    app: buildingblock
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: buildingblock