apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: standard-service-operator
rules:
  - apiGroups:
      - com.perfumeriasloli
    resources:
      - schemas
    verbs:
      - "*"
  - apiGroups:
      - com.perfumeriasloli
    resources:
      - schemas/status
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"